name=Go
extensions=go
shebangs=
patterns=PACKAGE:^package\\s+(\\w+);IMPORT:^import\\s+;FUNC:^func\\s+(\\w+);TYPE:^type\\s+(\\w+);STRUCT:^type\\s+(\\w+)\\s+struct;INTERFACE:^type\\s+(\\w+)\\s+interface
