name=Java
extensions=java
shebangs=
patterns=PACKAGE:^package\\s+([\\w.]+);IMPORT:^import\\s+([\\w.]+);CLASS:^class\\s+(\\w+);INTERFACE:^interface\\s+(\\w+);ENUM:^enum\\s+(\\w+);ANNOTATION:@interface\\s+(\\w+)
