name=Scala
extensions=scala
shebangs=
patterns=PACKAGE:^package\\s+([\\w.]+);IMPORT:^import\\s+([\\w.]+);CLASS:^class\\s+(\\w+);TRAIT:^trait\\s+(\\w+);OBJECT:^object\\s+(\\w+);CASE_CLASS:^case class\\s+(\\w+);CASE_OBJECT:^case object\\s+(\\w+);DEF:^def\\s+(\\w+);VAL:^val\\s+(\\w+);VAR:^var\\s+(\\w+);TYPE:^type\\s+(\\w+);ENUM:^enum\\s+(\\w+)
