name=TypeScript
extensions=ts,tsx
shebangs=
patterns=IMPORT:^import\\s+.*from\\s+['"]([^'"]+)['"];EXPORT:^export\\s+(?:default\\s+)?(class|interface|type|function|const|enum)\\s+(\\w+);INTERFACE:^interface\\s+(\\w+);TYPE:^type\\s+(\\w+);CLASS:^class\\s+(\\w+);FUNCTION:^function\\s+(\\w+);ENUM:^enum\\s+(\\w+)
